[package]
name = "pirate"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde_bencode = "*"
serde_bytes = "*"
sha1 = "*"
anyhow = "*"
url = "*"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
